application:
  subdomain: nowen-reader
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://nowen-reader:3000/
services:
  nowen-reader:
    # cropflre/nowen-reader:v1.0.0
    # upstream: cropflre/nowen-reader:v1.0.12
    image: registry.lazycat.cloud/czyt/cropflre/nowen-reader:e4c74b91dd39351d
    environment:
      - GIN_MODE=release
      - DATABASE_URL=/data/nowen-reader.db
      - COMICS_DIR=/app/comics
      - DATA_DIR=/app/.cache
      - PORT=3000
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/cache/nowen:/app/.cache
      - /lzcapp/var/comics:/app/comics
